# Generated by Django 5.1.7 on 2025-03-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('polygon_coors', models.JSONField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ForestClassificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_map', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='api_forest.forestmodel')),
            ],
        ),
        migrations.CreateModel(
            name='IndicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NDVI', 'Ndvi'), ('NDWI', 'Ndwi'), ('EVI', 'Evi'), ('NBR', 'Nbr'), ('SAVI', 'Savi'), ('GNDVI', 'Gndvi'), ('SIPI', 'Sipi'), ('MGRVI', 'Mgrvi'), ('TGI', 'Tgi'), ('VARI', 'Vari'), ('GRVI', 'Grvi'), ('SR', 'Sr'), ('CI', 'Ci'), ('MSR', 'Msr'), ('OSAVI', 'Osavi'), ('NDMI', 'Ndmi'), ('MSAVI', 'Msavi'), ('NDRI', 'Ndri'), ('RECI', 'Reci')], max_length=250)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='api_forest.forestmodel')),
            ],
        ),
    ]
