# Generated by Django 5.1.7 on 2025-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_forest', '0002_alter_forestmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
