# Generated by Django 5.1.7 on 2025-03-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_forest', '0004_rename_array_map_forestclassificationmodel_forest_mask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForestClassificationModel',
            new_name='ForestMaskModel',
        ),
    ]
