# Generated by Django 5.1.7 on 2025-03-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_forest', '0005_rename_forestclassificationmodel_forestmaskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestmodel',
            name='unique_id',
            field=models.CharField(default='forest', max_length=250),
            preserve_default=False,
        ),
    ]
