# Generated by Django 5.1.7 on 2025-03-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_forest', '0006_forestmodel_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicesmodel',
            name='name',
            field=models.CharField(choices=[('NDVI', 'Ndvi'), ('NDWI', 'Ndwi'), ('EVI', 'Evi'), ('NBR', 'Nbr'), ('SAVI', 'Savi'), ('GNDVI', 'Gndvi'), ('SIPI', 'Sipi'), ('MGRVI', 'Mgrvi'), ('TGI', 'Tgi'), ('VARI', 'Vari'), ('GRVI', 'Grvi'), ('SR', 'Sr'), ('CI', 'Ci'), ('MSR', 'Msr'), ('OSAVI', 'Osavi'), ('NDMI', 'Ndmi'), ('MSAVI', 'Msavi'), ('NDRI', 'Ndri'), ('RECI', 'Reci'), ('NDRE', 'Ndre')], max_length=250),
        ),
    ]
