# Generated by Django 5.1.7 on 2025-03-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_forest', '0008_alter_indicesmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmaskmodel',
            name='forest_mask',
            field=models.URLField(),
        ),
    ]
