# Generated by Django 5.1.7 on 2025-03-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_forest', '0009_alter_forestmaskmodel_forest_mask'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnedMaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burned_mask', models.URLField()),
                ('timestamp', models.DateTimeField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burned', to='api_forest.forestmodel')),
            ],
        ),
    ]
