# Generated by Django 5.1.7 on 2025-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_forest', '0010_burnedmaskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestmaskmodel',
            name='tiff_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='burnedmaskmodel',
            name='burned_mask',
            field=models.ImageField(upload_to='files/burned_masks/'),
        ),
        migrations.AlterField(
            model_name='forestmaskmodel',
            name='forest_mask',
            field=models.ImageField(upload_to='files/forest_masks/'),
        ),
    ]
