# Generated by Django 5.1.7 on 2025-04-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_forest', '0011_forestmaskmodel_tiff_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestmodel',
            name='unique_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
